version: '3.7'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: apps_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "5000:5000"
    networks:
      - gropoz-network
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: apps_production_postgres
    container_name: apps_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - gropoz-network
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - gropoz-network

  celery_worker:
    <<: *django
    image: apps_local_celery_worker
    container_name: apps_local_celery_worker
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-worker
    networks:
      - gropoz-network

  celery_beat:
    <<: *django
    image: apps_local_celery_beat
    container_name: apps_local_celery_beat
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-beat
    networks:
      - gropoz-network

networks:
    gropoz-network:
      external: true

